Repository DontKnowers/ForMat-Intellij-Plugin, pull requests merged in 2020-05, with the labels that each got.

#1 Updated readme
  README.md
Labels: documentation

#6 Added engine blanks
  build.gradle
  src/main/java/com/plugin/HelloAction.java
  src/main/java/com/plugin/engine/JavaFormatter.java
  src/main/java/com/plugin/engine/LanguageFormatter.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#9 Added gradle.properties with heap-size change
  gradle.properties
Labels: bug

#10 Added plugin description
  src/main/resources/META-INF/plugin.xml
Labels: documentation

#11 Implemented engine blanks
  settings.gradle
  src/main/java/com/plugin/engine/FileChanges.java
  src/main/java/com/plugin/engine/JavaFormatter.java
  src/main/java/com/plugin/engine/LanguageFormatter.java
Labels: enhancement

#15 Add unit tests
  src/main/java/com/plugin/engine/FileChanges.java
  src/main/java/com/plugin/engine/JavaFormatter.java
  src/test/java/com/plugin/engine/FileFormatterTest.java
  src/test/java/com/plugin/engine/FormatterTest.java
  src/test/java/com/plugin/engine/PartsFileFormatterTest.java
  src/test/java/com/plugin/engine/TypeFormatterTest.java
  src/test/resources/java/samples/1.java
  src/test/resources/java/samples/1_ans.java
  src/test/resources/java/samples/2.java
  src/test/resources/java/samples/2_ans.java
  src/test/resources/java/samples/3.java
  src/test/resources/java/samples/3_ans.java
  src/test/resources/java/samples/4.java
  src/test/resources/java/samples/4_ans.java
  src/test/resources/java/type_formatting/AOSPFormattingType.java
  src/test/resources/java/type_formatting/FormattingTypeSample.java
  src/test/resources/java/type_formatting/GoogleFormattingType.java
Labels: test

#16 Added drop-down menu for plugin
  src/main/java/com/plugin/frontend/actions/FormatAreaAction.java
  src/main/java/com/plugin/frontend/actions/FormatDiffAction.java
  src/main/java/com/plugin/frontend/actions/FormatFileAction.java
  src/main/resources/META-INF/plugin.xml
Labels: enhancement
